# Generated by Django 5.0.1 on 2024-01-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=14)),
                ('profile_pic', models.ImageField(upload_to='profile_pic/')),
                ('guardian', models.CharField(max_length=50)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('guardian_phone_number', models.CharField(max_length=14)),
                ('relationship_with_guardian', models.CharField(max_length=20)),
                ('house', models.CharField(choices=[('africa', 'AFRICA'), ('agarkhan', 'AGARKHAN'), ('kakunguru', 'KAKUNGURU'), ('luwangula', 'LUWANGULA')], max_length=10)),
                ('club', models.CharField(choices=[('interact', 'INTERACT'), ('aids', 'AIDS'), ('rotery', 'ROTERY'), ('nkobazambogo', 'NKOBAZAMBOGO'), ('kmsa', 'KMSA')], max_length=20)),
                ('current_class', models.CharField(choices=[('f1', 'F1'), ('f2', 'F2'), ('f3', 'F3'), ('f4', 'F4'), ('f5', 'F5'), ('f6', 'F6')], max_length=10)),
                ('stream', models.CharField(max_length=10)),
                ('religion', models.CharField(choices=[('islam', 'ISLAM'), ('christianity', 'CHRISTIANITY')], max_length=20)),
                ('gender', models.CharField(choices=[('male', 'MALE'), ('female', 'FEMALE')], max_length=10)),
                ('student_number', models.CharField(max_length=8)),
                ('date_of_birth', models.DateField()),
                ('date_joined', models.DateField()),
                ('date_left', models.DateField(blank=True, null=True)),
                ('combination', models.CharField(blank=True, max_length=20, null=True)),
                ('disabled', models.BooleanField()),
                ('disabled_description', models.TextField(blank=True, null=True)),
                ('any_chronic_disease_condition', models.BooleanField()),
                ('chronic_disease_condition_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'ACTIVE'), ('inactive', 'INACTIVE')], default='inactive', max_length=20)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
