# Generated by Django 5.0.1 on 2024-01-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('class_level', models.CharField(choices=[('f1', 'F1'), ('f2', 'F2'), ('f3', 'F3'), ('f4', 'F4'), ('f5', 'F5'), ('f6', 'F6')], max_length=20)),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
    ]
