# Generated by Django 5.0.1 on 2024-01-17 11:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=14, validators=[django.core.validators.MinLengthValidator(limit_value=10, message='Phone number must not be less than 10 digits')])),
                ('gender', models.CharField(max_length=8)),
                ('address', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='teachers_pics/')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('classes_taught', models.CharField(max_length=100)),
                ('date_joined', models.DateField(auto_now_add=True)),
                ('subjects_taught', models.ManyToManyField(blank=True, to='subjects.subject')),
            ],
            options={
                'verbose_name': 'Teacher',
                'verbose_name_plural': 'Teachers',
            },
        ),
    ]
