# Generated by Django 5.0.1 on 2024-01-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=6)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(max_length=50)),
                ('current_class', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=50)),
                ('school_location', models.CharField(max_length=30)),
                ('school_phone_number', models.CharField(max_length=20)),
                ('change_reason', models.TextField()),
                ('date_of_application', models.DateTimeField(auto_now_add=True)),
                ('class_applied_for', models.CharField(max_length=20)),
                ('recommendation_letter', models.FileField(blank=True, null=True, upload_to='recommendation_letters/')),
                ('passport_photo', models.ImageField(upload_to='passport_photos/')),
                ('results_document', models.FileField(upload_to='results_documents/')),
                ('guardian_name', models.CharField(max_length=30)),
                ('guardian_phone_number', models.CharField(max_length=20)),
                ('guardian_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('relationship_with_guardian', models.CharField(max_length=20)),
                ('religion', models.CharField(choices=[('Islam', 'Islam'), ('Christianity', 'Christianity')], max_length=20)),
                ('combination_applied_for', models.CharField(blank=True, max_length=20, null=True)),
                ('disabled', models.BooleanField()),
                ('disabled_description', models.TextField(blank=True, null=True)),
                ('any_chronic_disease_condition', models.BooleanField()),
                ('chronic_disease_condition_description', models.TextField(blank=True, null=True)),
                ('application_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=30)),
            ],
            options={
                'verbose_name': 'Application',
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
